### ISSUE TITLE
cannot edit 'local' credentials

### ISSUE THREAD

**Issue by travisghansen** [redconnect-io/node-red-contrib-twilio#1]
I've created a 'local' set of credentials. After doing so clicking the edit pencil with the resource selected yields the edit node screen sliding right and disappearing without the edit form reappearing with a subsequently slide left.

Thanks!

**Comment by travisghansen** [comment]
I was also asked to let you know that the source link for this project here ```https://www.npmjs.com/package/node-red-node-twilio``` is actually pointing to ```https://github.com/node-red/node-red-nodes/blob/master/social``` instead of this project.  You may want to update.

**Comment by retailos** [comment]
Hi @travisghansen there are actually 2 packages:

https://www.npmjs.com/package/node-red-node-twilio and
https://www.npmjs.com/package/node-red-contrib-twilio

The first is maintained by Nick and his team at IBM. so its probably best to use that one. 

Thanks.

**Comment by travisghansen** [comment]
@retailos I failed to notice I had 2 nodes.  This is a case of both sides pointing the finger at each other but I'm glad you pointed that out because the issue appears to be with their plugin.  I initially opened the ticket over there but erroneously gave it the wrong name.

https://github.com/node-red/node-red-nodes/issues/233
